"""first migration

Revision ID: ab11c13ea207
Revises: 
Create Date: 2022-03-10 20:33:59.148189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab11c13ea207'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('activity_name', sa.String(length=150), nullable=False),
    sa.Column('sense', sa.String(length=50), nullable=False),
    sa.Column('age_range', sa.String(length=50), nullable=False),
    sa.Column('supplies', sa.String(length=300), nullable=False),
    sa.Column('instructions', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
